version: '3.8'
name: local-postgres
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5434:5434'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - shared-net
    command: ["postgres", "-c", "wal_level=logical", "-p 5434" ]
    

# networks:
#   my-proxy-net:
#     external:
#       name: local-airflow_default 
networks:
  shared-net:
      external: true
      name: shared-net
      

volumes:
  db:
    driver: local
    
# networks:
#   - bridge